Following <https://scikit-learn.org/stable/modules/impute.html>

Consider comparing learning performance for different imputers: multiple vs single imputation 

In [8]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer, KNNImputer

train = [[1, 2], [np.nan, 3], [7, 6]]
test = [[np.nan, 2], [6, np.nan], [17, 16]]

dTrain = pd.DataFrame([["a", "x"], [np.nan, "y"], ["a", np.nan], ["b", "y"]], dtype="category")

## Simple Imputer

In [3]:
imp = SimpleImputer(strategy='mean')
imp.fit_transform(train)

array([[1., 2.],
       [4., 3.],
       [7., 6.]])

In [5]:
imp.transform(test)

array([[ 4.        ,  2.        ],
       [ 6.        ,  3.66666667],
       [17.        , 16.        ]])

In [7]:
SimpleImputer(strategy="most_frequent").fit_transform(dTrain)

array([['a', 'x'],
       ['a', 'y'],
       ['a', 'y'],
       ['b', 'y']], dtype=object)

## Nearest neighbour

In [10]:
X = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]
KNNImputer(n_neighbors=2, weights="uniform").fit_transform(X)

array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])