In [1]:
import numpy as np

A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

In [4]:
A * 3

array([[3, 3],
       [0, 3]])

In [5]:
np.sin(A)

array([[0.84147098, 0.84147098],
       [0.        , 0.84147098]])

In [2]:
A * B

array([[2, 0],
       [0, 4]])

In [3]:
A.dot(B)

array([[5, 4],
       [3, 4]])