In [1]:
import numpy as np

In [7]:
np.array([1, 2])

array([1, 2])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.full(5, 1.4)

array([1.4, 1.4, 1.4, 1.4, 1.4])

## Arrange

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

## Linspace

In [5]:
np.linspace(0, np.pi, 10)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

## Random

In [6]:
np.random.default_rng(13).random((2, 3))

array([[0.86479759, 0.85530251, 0.8110234 ],
       [0.26144636, 0.07719946, 0.94646578]])

## Copy

In [13]:
np.ones(3).copy()

array([1., 1., 1.])