In [3]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.mod(arr, 3)==0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [5]:
np.extract(np.mod(arr, 3)==0, arr)

array([0, 3, 6, 9])

In [6]:
np.count_nonzero(np.extract(np.mod(arr, 3)==0, arr))

3