In [4]:
import numpy as np

x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

Returns a tuple of arrays, one for each dimension of a, containing the indices of the non-zero elements in that dimension. 

In [3]:
np.nonzero(x)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [5]:
np.flatnonzero(x)

array([0, 4, 6, 7])

In [6]:
np.count_nonzero(x)

4