In [2]:
import numpy as np

X = np.array([[ 1., -1.,  2.], [ 2.,  0.,  0.], [ 0.,  1., -1.]])

In [3]:
X.mean(axis=0)

array([1.        , 0.        , 0.33333333])

In [4]:
X.std(axis=0)

array([0.81649658, 0.81649658, 1.24721913])

In [5]:
X.min(axis=0)

array([ 0., -1., -1.])

In [6]:
X.min(axis=1)

array([-1.,  0., -1.])

In [7]:
np.percentile(X[:, 0], [0, 25, 50, 75, 100])

array([0. , 0.5, 1. , 1.5, 2. ])